name: Android CI

on:
  push:
    branches: [ "feat/video-creation-phase2" ]
  pull_request:
    branches: [ "feat/video-creation-phase2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks

      - name: Create Signing Configs
        run: |
          mkdir -p ~/.gradle
            echo "MYAPP_UPLOAD_STORE_FILE=keystore.jks" >> ~/.gradle/gradle.properties
            echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}" >> ~/.gradle/gradle.properties
            echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}" >> ~/.gradle/gradle.properties
            echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}" >> ~/.gradle/gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean Gradle
        run: ./gradlew clean

      - name: Build Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
          retention-days: 7
          compression-level: 6
          overwrite: true
